name: Run npm publish script

on:
  push:
    branches:
      - main  # Or 'master' or any branch you want

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Or your project's Node version

      - name: Install dependencies
        run: npm install

      - name: Run npm publish script
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
